# Generated by Django 4.1.7 on 2023-03-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainInfoResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('Female', 'Женский'), ('Male', 'Мужской')], max_length=10, verbose_name='Пол')),
                ('city', models.CharField(max_length=50, verbose_name='Город проживания')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
        ),
        migrations.CreateModel(
            name='UserNationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nationality'],
            },
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/user_id', verbose_name='Фотография')),
                ('id_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.maininforesume')),
            ],
        ),
        migrations.AddField(
            model_name='maininforesume',
            name='nationality',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.PROTECT, to='resume.usernationality', verbose_name='Гражданство'),
        ),
    ]
