# Generated by Django 4.1.7 on 2023-03-26 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maininforesume',
            name='photo',
        ),
        migrations.AlterField(
            model_name='maininforesume',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='maininforesume',
            name='nationality',
            field=models.ForeignKey(default=60, on_delete=django.db.models.deletion.PROTECT, to='resume.usernationality', verbose_name='Гражданство'),
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='photos/user_id', verbose_name='Фотография')),
                ('id_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.maininforesume')),
            ],
        ),
    ]
